services:
  backend:
    build:
      context: ./../
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./../:/home/kidhhs_assignment
    hostname: backend
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5
  frontend:
    build:
      context: ./../
      dockerfile: docker/frontend/Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./../:/home/kidhhs_assignment
    hostname: frontend

